name: 'Mosquitto MQTT Broker in GitHub Actions'
description: 'Start a Mosquitto message broker (on default port 1883 & 9001 for WebSockets)'

branding:
  icon: 'message-square'
  color: 'red'

inputs:
  version:
    description: 'Mosquitto version to use'
    required: false
    default: 'latest'
  ports:
    description: 'Port mappings in a [host]:[container] format, delimited by spaces (example: "1883:1883 8883:8883")'
    required: false
    default: '1883:1883'
  certificates:
    description: 'Absolute path to a directory containing certificate files which can be referenced in the config (the folder is mounted under `/mosquitto-certs`)'
    required: false
    default: ''
  config:
    description: 'Absolute path to the mosquitto.conf configuration file to use'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
