name: 'HiveMQ 4 MQTT Broker in GitHub Actions'
description: 'Start a HiveMQ 4 message broker with configurable ports and TLS'

branding:
  icon: 'message-square'
  color: 'red'

inputs:
  version:
    description: 'HiveMQ 4 version to use'
    required: false
    default: 'latest'
  ports:
    description: 'Port mappings in a [host]:[container] format, delimited by spaces (example: "1883:1883 8883:8883")'
    required: false
    default: '1883:1883'
  certificates:
    description: 'Absolute path to a directory containing certificate files which can be referenced in the config (the folder is mounted under `/hivemq-certs`)'
    required: false
    default: ''
  config:
    description: 'Absolute path to the config.xml configuration file to use'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.ports }}
    - ${{ inputs.certificates }}
    - ${{ inputs.config }}
