name: 'PR: Verify Code Style'

on: pull_request

jobs:
  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PHP_CodeSniffer inspection
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true
